include:
    - board: seeeduino_xiao_ble
      shield: ergonaut_one_left
      snippet: zmk-usb-logging
      cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_STUDIO=y
    - board: seeeduino_xiao_ble
      shield: ergonaut_one_right
      snippet: zmk-usb-logging
      cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_STUDIO=y
    - board: seeeduino_xiao_ble
      shield: settings_reset
    - board: seeeduino_xiao_ble
      shield: ergonaut_one_dongle dongle_screen
      # shield: ergonaut_one_dongle prospector_adapter
      snippet: zmk-usb-logging
      cmake-args: -DCONFIG_ZMK_STUDIO=y
