manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: janpfischer
          url-base: https://github.com/janpfischer
        - name: Xeanloo
          url-base: https://github.com/Xeanloo
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
        # - name: zmk-dongle-screen
        #   remote: janpfischer
        #   revision: main
        - name: zmk-dongle-screen
          remote: Xeanloo
          revision: last_words
        # - name: prospector-zmk-module
        #   remote: Xeanloo
        #   revision: main
    self:
        path: config
