manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: ergonautkb
          url-base: https://github.com/ergonautkb
        - name: carrefinho # <--- add this
          url-base: https://github.com/carrefinho
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
        - name: ergonautkb-zmk-module
          remote: ergonautkb
          revision: main
    self:
        path: config
