manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: ergonautkb
          url-base: https://github.com/ergonautkb
        # - name: janpfischer
        # url-base: https://github.com/janpfischer
        - name: tokyo2006 # <--- add this
          url-base: https://github.com/tokyo2006
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
        - name: ergonautkb-zmk-module
          remote: ergonautkb
          revision: main
        # - name: zmk-dongle-screen
        #   remote: janpfischer
        #   revision: main
        - name: prospector-zmk-module # <--- and these
          remote: tokyo2006 # <---
          revision: main
    self:
        path: config
