manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: ergonautkb
          url-base: https://github.com/ergonautkb
        # - name: janpfischer
        #   url-base: https://github.com/janpfischer
        - name: carrefinho # <--- add this
          url-base: https://github.com/carrefinho
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: 147c340c6e8d377304acfdd64dc86cf83ebdfef2
          import: app/west.yml
        - name: ergonautkb-zmk-module
          remote: ergonautkb
          revision: main
        # - name: zmk-dongle-screen
        #   remote: janpfischer
        #   revision: main
        - name: prospector-zmk-module # <--- and these
          remote: carrefinho # <---
          revision: main
    self:
        path: config
